name: GFSLT-VLP
data:
  train_label_path: ./data/Phonexi-2014T/labels.train
  dev_label_path: ./data/Phonexi-2014T/labels.dev
  test_label_path: ./data/Phonexi-2014T/labels.test
  img_path: /home1/hoho/datasets/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-210x260px/
  max_length: 300
training:
  wandb: online # online or disabled
  scale_embedding: False
model:
  tokenizer: /home1/hoho/sync/GFSLT-VLP/pretrain_models/MBart_trimmed
  transformer:  /home1/hoho/sync/GFSLT-VLP/pretrain_models/MBart_trimmed
  visual_encoder: /home1/hoho/sync/GFSLT-VLP/pretrain_models/mytran
  sign_proj: True
